version: '3'

services:

  frontend:
    container_name: app_frontend
    build: ./frontend
    restart: 'always'
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./backend/app
    restart: 'always'
    ports:
      - 3001:3001
    command: npm run dev
    volumes:
      - './backend/app/src:/app/src'
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql
    restart: "always"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'America/Sao_Paulo'
